### ISSUE TITLE
Where is train.py?

### ISSUE THREAD

**Issue by JuChanSeo** [moboehle/B-cos#2]
Hi, Thanks for your interesting paper.
I'm trying to train your model but only I can find is Trainer class in training folder and not the training loop code.
Can you please add your code for training loop code OR
give some guidelines for reproducing your implementation?

Thanks a lot.

**Comment by nps1ngh** [comment]
Hey,

check out the `README.md` file here: https://github.com/moboehle/B-cos/tree/main/experiments

**Comment by JuChanSeo** [comment]
> Hey,
> 
> check out the `README.md` file here: https://github.com/moboehle/B-cos/tree/main/experiments

Thanks a lot. It seems like I didn't check carefully
