### ISSUE TITLE
Cannot train on TinyImagenet

### ISSUE THREAD

**Issue by saa025** [moboehle/B-cos#6]
Hello,

I attempting to run one of the basic experiments with the TinyImagenet dataset. Below are the steps I've taken and the issues I am running into. I would very much appreciate any help.

I've downloaded the tiny-imagenet-200 dataset from the following locations: http://cs231n.stanford.edu/tiny-imagenet-200.zip

I unzipped to the ./data folder where I then resorted the data into the expected format for the train and val folders. The directory structure is as follows:

```
tiny-imagenet-200
    train/
        class1/
            sample1.jpg
            sample2.jpg
            ...
        class2/
            sample1.jpg
            sample2.jpg
            ...
    val/
        class1/
            sample1.jpg
            sample2.jpg
            ...
        class2/
            sample1.jpg
            sample2.jpg
            ...
```

I then tried to run the experiment for Imagenet on this dataset with the following command:

`py experiments/Imagenet/bcos/model.py --single_epoch=true --experiment_name=resnet_34 --dataset_name=TinyImagenet --model_config=bcos`

It seems like it loads up the data but errors out with the following:

![image](https://user-images.githubusercontent.com/42306206/226795344-3c909028-ef51-4fbb-9c7a-4c99eb0ea9c1.png)

I then assumed that there may be something wrong with the data loader so I then attempted to simply load the data and iterate through the Dataloader. This is the result:

![image](https://user-images.githubusercontent.com/42306206/226795804-f3babf44-98b2-4fce-8a9d-d46dc1fc06ba.png)
 

Not sure if I am doing anything wrong. Any input would be appreciated. 

Thanks

**Comment by nps1ngh** [comment]
Hi, this seems to be related to [numpy deprecating `np.int`](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). 

You could try changing https://github.com/moboehle/B-cos/blob/452ff6bf8d043783276ab40b1ccfcacebfbdb4f5/data/augmentations/rand_augment.py#L84

to 

```python
img_np = np.array(img).astype(int) 
```

---

The `OneHot` transform takes the number of classes to initialize, your second error seems to suggest that it has the wrong number of classes. For TinyImageNet you have 200 classes but the transform apparently got 10 as the number. You should try looking into changing that.

---

Also make sure you add the appropriate configs for TinyImagenet in https://github.com/moboehle/B-cos/tree/main/experiments
As you can see it currently only has configs for Imagenet and CIFAR10, you will need to add your custom ones for TinyImagenet yourself.
